import type { Food } from './types'

export const defaultPantry: Food[] = [
  {
    id: 'yogurt',
    name: 'Yogurt',
    emoji: '🥛',
    cost: 2,
    prepMinutes: 1,
    packable: true,
    calories: 150,
    reactions: {
      baby:  { tone: 'ideal', message: 'Yum, smooth! 😊' },
      child: { tone: 'okay',  message: "Eh, it's fine." },
      adult: { tone: 'ideal', message: 'Protein. Perfect.' },
      elder: { tone: 'ideal', message: 'Gentle and lovely.' },
    },
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal',
    emoji: '🥣',
    cost: 1,
    prepMinutes: 5,
    packable: false,
    calories: 200,
    reactions: {
      baby:  { tone: 'ideal', message: 'Mmm warm!' },
      child: { tone: 'ideal', message: 'Big bowl please!' },
      adult: { tone: 'okay',  message: 'Solid.' },
      elder: { tone: 'ideal', message: 'Easy on the stomach.' },
    },
  },
  {
    id: 'bread',
    name: 'Bread',
    emoji: '🍞',
    cost: 1,
    prepMinutes: 1,
    packable: true,
    calories: 80,
    reactions: {
      baby:  { tone: 'poor', message: 'Just bread? Hmm.' },
      child: { tone: 'okay', message: 'Need more than this!' },
      adult: { tone: 'okay', message: 'Bread alone? Sigh.' },
      elder: { tone: 'okay', message: 'A bit dry today.' },
    },
  },
  {
    id: 'apple',
    name: 'Apple',
    emoji: '🍎',
    cost: 2,
    prepMinutes: 1,
    packable: true,
    calories: 100,
    reactions: {
      baby:  { tone: 'bad',   message: 'Too hard for me!' },
      child: { tone: 'ideal', message: 'Crunch crunch!' },
      adult: { tone: 'ideal', message: 'Fresh and quick.' },
      elder: { tone: 'okay',  message: 'Tough on my teeth.' },
    },
  },
  {
    id: 'eggs',
    name: 'Eggs',
    emoji: '🥚',
    cost: 2,
    prepMinutes: 6,
    packable: false,
    calories: 150,
    reactions: {
      baby:  { tone: 'poor',  message: 'Tummy ache...' },
      child: { tone: 'ideal', message: 'Protein power!' },
      adult: { tone: 'ideal', message: 'Yes, fuel.' },
      elder: { tone: 'ideal', message: 'Soft protein. Good.' },
    },
  },
  {
    id: 'coffee',
    name: 'Coffee',
    emoji: '☕',
    cost: 3,
    prepMinutes: 4,
    packable: false,
    calories: 5,
    reactions: {
      baby:  { tone: 'bad',   message: "Babies can't have coffee!" },
      child: { tone: 'bad',   message: "Coffee isn't for kids!" },
      adult: { tone: 'ideal', message: 'Bless you. ☕' },
      elder: { tone: 'okay',  message: "I'll be jittery..." },
    },
  },
]
