import type { Food } from './types'

export const defaultPantry: Food[] = [
  // ----- Dairy / protein staples -----
  {
    id: 'yogurt',
    name: 'Yogurt',
    emoji: '🥛',
    cost: 2,
    prepMinutes: 1,
    packable: true,
    calories: 150,
    reactions: {
      baby:  { tone: 'ideal', message: 'Yum, smooth! 😊' },
      child: { tone: 'okay',  message: "Eh, it's fine." },
      adult: { tone: 'ideal', message: 'Protein. Perfect.' },
      elder: { tone: 'ideal', message: 'Gentle and lovely.' },
    },
  },
  {
    id: 'feta',
    name: 'Feta cheese',
    emoji: '🧀',
    cost: 3,
    prepMinutes: 1,
    packable: true,
    calories: 75,
    reactions: {
      baby:  { tone: 'poor',  message: 'Too salty for me!' },
      child: { tone: 'okay',  message: 'Crumbly... bit salty.' },
      adult: { tone: 'ideal', message: 'Salty and rich. Yes.' },
      elder: { tone: 'okay',  message: 'Watching my salt.' },
    },
  },
  {
    id: 'eggs',
    name: 'Eggs',
    emoji: '🥚',
    cost: 2,
    prepMinutes: 6,
    packable: false,
    calories: 150,
    reactions: {
      baby:  { tone: 'poor',  message: 'Tummy ache...' },
      child: { tone: 'ideal', message: 'Protein power!' },
      adult: { tone: 'ideal', message: 'Yes, fuel.' },
      elder: { tone: 'ideal', message: 'Soft protein. Good.' },
    },
  },
  {
    id: 'fish',
    name: 'Fish',
    emoji: '🐟',
    cost: 4,
    prepMinutes: 12,
    packable: false,
    calories: 200,
    reactions: {
      baby:  { tone: 'poor',  message: 'Bones scare me!' },
      child: { tone: 'ideal', message: 'Pink fish, yum!' },
      adult: { tone: 'ideal', message: 'Omega-3 perfection.' },
      elder: { tone: 'ideal', message: 'Good for the heart.' },
    },
  },

  // ----- Carbs / grains -----
  {
    id: 'bread',
    name: 'Bread',
    emoji: '🍞',
    cost: 1,
    prepMinutes: 1,
    packable: true,
    calories: 80,
    reactions: {
      baby:  { tone: 'poor', message: 'Just bread? Hmm.' },
      child: { tone: 'okay', message: 'Need more than this!' },
      adult: { tone: 'okay', message: 'Bread alone? Sigh.' },
      elder: { tone: 'okay', message: 'A bit dry today.' },
    },
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal',
    emoji: '🥣',
    cost: 1,
    prepMinutes: 5,
    packable: false,
    calories: 200,
    reactions: {
      baby:  { tone: 'ideal', message: 'Mmm warm!' },
      child: { tone: 'ideal', message: 'Big bowl please!' },
      adult: { tone: 'okay',  message: 'Solid.' },
      elder: { tone: 'ideal', message: 'Easy on the stomach.' },
    },
  },
  {
    id: 'rice',
    name: 'Rice',
    emoji: '🍚',
    cost: 1,
    prepMinutes: 15,
    packable: false,
    calories: 200,
    reactions: {
      baby:  { tone: 'ideal', message: 'Soft and easy!' },
      child: { tone: 'okay',  message: 'Plain rice? Need more!' },
      adult: { tone: 'okay',  message: 'Carbs — solid.' },
      elder: { tone: 'ideal', message: 'Easy on me.' },
    },
  },

  // ----- Fruit & veg -----
  {
    id: 'apple',
    name: 'Apple',
    emoji: '🍎',
    cost: 2,
    prepMinutes: 1,
    packable: true,
    calories: 100,
    reactions: {
      baby:  { tone: 'bad',   message: 'Too hard for me!' },
      child: { tone: 'ideal', message: 'Crunch crunch!' },
      adult: { tone: 'ideal', message: 'Fresh and quick.' },
      elder: { tone: 'okay',  message: 'Tough on my teeth.' },
    },
  },
  {
    id: 'banana',
    name: 'Banana',
    emoji: '🍌',
    cost: 1,
    prepMinutes: 1,
    packable: true,
    calories: 100,
    reactions: {
      baby:  { tone: 'ideal', message: 'Mash-able! Love it!' },
      child: { tone: 'ideal', message: 'Quick energy!' },
      adult: { tone: 'okay',  message: 'Sweet — okay snack.' },
      elder: { tone: 'okay',  message: 'Soft, fine for me.' },
    },
  },
  {
    id: 'tomato',
    name: 'Tomato',
    emoji: '🍅',
    cost: 1,
    prepMinutes: 1,
    packable: true,
    calories: 25,
    reactions: {
      baby:  { tone: 'okay',  message: 'Squishy! 😋' },
      child: { tone: 'okay',  message: 'Plain tomato?' },
      adult: { tone: 'ideal', message: 'Fresh and bright.' },
      elder: { tone: 'ideal', message: 'Light and easy.' },
    },
  },
  {
    id: 'olives',
    name: 'Olives',
    emoji: '🫒',
    cost: 2,
    prepMinutes: 1,
    packable: true,
    calories: 30,
    reactions: {
      baby:  { tone: 'bad',   message: 'Choking risk for me!' },
      child: { tone: 'okay',  message: 'Salty... I guess.' },
      adult: { tone: 'ideal', message: 'Mediterranean staple.' },
      elder: { tone: 'okay',  message: 'Watching my salt.' },
    },
  },

  // ----- Sweets & drinks -----
  {
    id: 'honey',
    name: 'Honey',
    emoji: '🍯',
    cost: 2,
    prepMinutes: 1,
    packable: true,
    calories: 60,
    reactions: {
      baby:  { tone: 'bad',   message: 'Honey is dangerous for babies! 😟' },
      child: { tone: 'okay',  message: 'Sweet treat!' },
      adult: { tone: 'okay',  message: 'A bit sugary, but ok.' },
      elder: { tone: 'okay',  message: 'Sweet, in moderation.' },
    },
  },
  {
    id: 'cookie',
    name: 'Cookie',
    emoji: '🍪',
    cost: 2,
    prepMinutes: 1,
    packable: true,
    calories: 100,
    reactions: {
      baby:  { tone: 'poor',  message: 'Hard and sugary.' },
      child: { tone: 'okay',  message: 'A treat! 🍪' },
      adult: { tone: 'okay',  message: 'A small indulgence.' },
      elder: { tone: 'okay',  message: 'Watching my sugar.' },
    },
  },
  {
    id: 'coffee',
    name: 'Coffee',
    emoji: '☕',
    cost: 3,
    prepMinutes: 4,
    packable: false,
    calories: 5,
    reactions: {
      baby:  { tone: 'bad',   message: "Babies can't have coffee!" },
      child: { tone: 'bad',   message: "Coffee isn't for kids!" },
      adult: { tone: 'ideal', message: 'Bless you. ☕' },
      elder: { tone: 'okay',  message: "I'll be jittery..." },
    },
  },
]
